"""Notification-transport port for credential delivery.

This Protocol is the seam between domain code and the concrete notification
backend. Milestone 1 uses `ConsoleNotificationTransport` (stdout, dev-only);
milestone 2 will introduce `SmtpNotificationTransport`.

`CredentialNotification` is defined here alongside the Protocol so all
credential-related types are co-located with their transport contract.

IMPORTANT: `CredentialNotification.admin_password` is plaintext and
in-memory only (D-12). It must never be written to any DB column, logged
via structlog, placed in an event, or serialized to disk.
"""

from dataclasses import dataclass
from typing import Protocol, runtime_checkable
from uuid import UUID  # noqa: TC003 — runtime-resolved type in frozen dataclass field

__all__ = [
    "CredentialNotification",
    "NotificationTransport",
]


@dataclass(frozen=True, slots=True)
class CredentialNotification:
    """Payload for a single credential-delivery notification.

    Carries the Odoo admin credentials generated by the deployment adapter.
    All secret fields are plaintext and must be discarded immediately after
    the transport call completes (D-12).

    Attributes:
        recipient_email: Email address of the customer who receives credentials.
        instance_id: UUID of the provisioned instance (for logging reference).
        instance_url: Live URL of the Odoo instance (e.g. ``https://…``).
        admin_login: Odoo admin login name (typically same as ``recipient_email``).
        admin_password: Plaintext Odoo admin password.

    Note:
        Sensitive: never log admin_password, never serialize to DB.
    """

    recipient_email: str
    instance_id: UUID
    instance_url: str
    admin_login: str
    admin_password: str  # sensitive: never log, never serialize to DB


@runtime_checkable
class NotificationTransport(Protocol):
    """Port for sending credential notifications to customers.

    Implementations must handle delivery errors without raising to the caller
    (log and continue), unless the failure should block the convergence path.

    Milestone 1: ``ConsoleNotificationTransport`` (stdout, dev-only).
    Milestone 2: ``SmtpNotificationTransport``.
    """

    async def send_credentials(self, notification: CredentialNotification) -> None:
        """Send the provisioned credentials to the customer.

        Args:
            notification: The credential payload to deliver.

        Raises:
            Exception: Implementations may raise on unrecoverable delivery
                failure; callers should handle this gracefully.
        """
        ...
